<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cari_kelayakan_model extends CI_Model
{

    public $table = 'tbl_kelayakan';
    public $nik = 'nik';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->nik, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by nik
    function get_by_nik($nik)
    {
        $this->db->where($this->nik, $nik);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('nik', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('ktp', $q);
        $this->db->or_like('kk', $q);
        $this->db->or_like('surat_nikah', $q);
        $this->db->or_like('slip_gaji', $q);
        $this->db->or_like('surat_jaminan', $q);
        $this->db->or_like('rek_listrik', $q);
        $this->db->or_like('npwp', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->nik, $this->order);
        $this->db->like('nik', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('ktp', $q);
        $this->db->or_like('kk', $q);
        $this->db->or_like('surat_nikah', $q);
        $this->db->or_like('slip_gaji', $q);
        $this->db->or_like('surat_jaminan', $q);
        $this->db->or_like('rek_listrik', $q);
        $this->db->or_like('npwp', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($nik, $data)
    {
        $this->db->where($this->nik, $nik);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($nik)
    {
        $this->db->where($this->nik, $nik);
        $this->db->delete($this->table);
    }

}

/* End of file Books_model.php */
/* Location: ./application/models/Books_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-08-19 18:56:00 */
/* http://harviacode.com */